# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Define o script de teste que deve rodar toda vez
script:
  - python -m unittest -v test

# Definir o Deploy no Heroku
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: devopslab-nataliamilani